- bucket: !!binary |
    Z0FBQUFBQmFaSHVraTdCenlPMU5JdmVZX1VlZ0dHOGtZV2xMLTJuN0pjS0U3UklDanFfOGw1ZXhf
    am55S2FMSldvU2o2LUpkTWVoR0pZWkk0emg4UGMxQ0ZBTkZDbWUwMmdudmx0WVVveDBwMHZ4WWky
    NWFGM0U9
  created_at: '2018-01-03T10:55:42.854Z'
  email: 27b6f3ebc1535b4b11b1508ec7c7364c
  id: 5a4cb6ae8df9df36f12c16c5
  message: من یه دامنه و هاست دارم که به هم متصل بودن، تصورم این بود که میشه مثل CloudFlare
    این Netlify رو بین این دو قرار بدم، وارد Netlify شدم و دامنم رو به DNS Zone اضافه
    کردم، چهار تا NameServer داد که دامنم روی اونا تنظیم کردم، بعد تو Netlify اومدم
    توی قسمت DNS Records دو تا NameServer هاستم رو در قالب  NS وارد کردم، الان بعد
    یه روز دامنم به هاست متصل نمیشه. نمیدونم ایراد کارم کجاست؟
  name: روح اله
  page_id: /netlify
  reply_to: null
  website: ''
- bucket: !!binary |
    Z0FBQUFBQmFaSHVrR2R1RmNPbUNRLTNCNmRGNC0tcF9TeFd0UVdIY3RtS1FNU2ZBOE9MR3VOTHFT
    dkxGWVQ1Nlc5MU5DVlhHMzdGZEYtQTJta0xhdFFrU1QwT3h5NXJVbGxOMGMxN2V5ZXNMYzRrWTNF
    LTl5U0U9
  created_at: '2018-01-03T15:39:47.386Z'
  email: 0371f5b900b484368f9e1717d7d965b1
  id: 5a4cf9438df9df223b2c16c9
  message: "> تصورم این بود که میشه مثل CloudFlare این Netlify رو بین این دو قرار\
    \ بدم\r\n\r\nنتلیفای سایت دیگه‌ای رو نمی‌تونه سرو کنه. همه چیز باید رو خودش باشه.\
    \ مناسب سایتهای استاتیکه.\r\n\r\n> بعد تو Netlify اومدم توی قسمت DNS Records دو\
    \ تا NameServer هاستم رو در قالب NS وارد کردم\r\n\r\nاین قسمت فقط به درد تعریف\
    \ رکوردهای جدید می‌خوره. مثلا تعریف زیر دامنه برای ایمیل. نمی‌تونی هاستت خودت\
    \ رو اینجا وارد کنی.\r\n\r\nکلا نمی‌تونی از نتلیفای برای اضافه کردن https به سرور\
    \ یا هاست شخصی خودت استفاده کنی مگر اینکه استاتیک باشه و کاملا از روی نتلیفای\
    \ سرو بشه. مطلب رو اصلاح می‌کنم که باعث سردرگمی نشه."
  name: مهدی صادقی
  page_id: /netlify
  reply_to: null
  website: https://mehdix.ir
