name: GitHub Pages

on:
  push:
    branches:
      - master  # deploys when code is pushed to master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout website code
        uses: actions/checkout@v3

      # 2. Setup Ruby (required for Jekyll)
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # adjust to your Ruby version if needed

      # 3. Remove old Gemfile.lock if corrupted
      - name: Remove old lockfile
        run: rm -f Gemfile.lock

      # 4. Install Jekyll dependencies
      - name: Install dependencies
        run: bundle install

      # 5. Patch Jekyll config (optional, only if using repo name as baseurl)
      - name: Patch Jekyll config
        run: |
          echo "baseurl: /${REPO_NAME}" >> _config.yml
          echo "url: https://${GITHUB_ACTOR}.github.io" >> _config.yml
        env:
          REPO_NAME: ${{ github.event.repository.name }}

      # 6. Build the Jekyll site
      - name: Build website
        run: bundle exec jekyll build

      # 7. Deploy to GitHub Pages
      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
