name: github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: bundle install

      - name: Patch Jekyll config
        run: |
          echo "baseurl: /${REPO_NAME}" >> _config.yml
          echo "url: https://${GITHUB_ACTOR}.github.io" >> _config.yml
        env:
          REPO_NAME: ${{ github.event.repository.name }}

      - name: Build website
        run: bundle exec jekyll build

      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
