name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

      env:
         GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}

    - name: Remove Gemfile.lock
      run: rm -rf Gemfile.lock

    # - name: Build
    #   uses: agentd00nut/jekyll-build-optional-deploy-gh-pages@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
    #     GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
    #     DEPLOY_SITE: false
    #     REMOVE_GEMLOCK: true

    - name: Build
      uses: jerryjvl/jekyll-build-action@v1

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        #publish_branch: gh-pages
        publish_dir: ./_site
