name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    name: Deploy website
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout website code
      uses: actions/checkout@v2

    # Remove this step if you bring your own domain.
    - name: Patch Jekyll config
      run: |
        echo "baseurl: /$REPO_NAME" >> _config.yml
        echo "url: https://$GITHUB_ACTOR.github.io" >> _config.yml
      env:
         GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
         REPO_NAME: ${{ github.event.repository.name }}

    # Why? In order to avoid bundler version mismatch (happend to me).
    - name: Remove Gemfile.lock
      run: rm -rf Gemfile.lock

    - name: Build website
      uses: jerryjvl/jekyll-build-action@v1

    - name: Deploy website
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
